# Файла csv в DataFrame

Чтение файла csv и его переделка.   
Переделать нужно поля с датой и временем (объеденить в одно поле и сделать по нему индекс)

In [11]:
import pandas as pd

In [12]:
# Загрузка данных их файла в df (указывем конкретный файл)
df_data = pd.read_csv('../data_finam/SPFB.RTS_20200103_20200103_5min.csv')  # Загрузка данных их файла в df
df_data

,<TICKER>,<PER>,<DATE>,<TIME>,<OPEN>,<HIGH>,<LOW>,<CLOSE>,<VOL>
0,SPFB.RTS,5,20200103,100000,154670.0,156720.0,154670.0,156610.0,13396
1,SPFB.RTS,5,20200103,100500,156600.0,156680.0,156500.0,156610.0,4957
2,SPFB.RTS,5,20200103,101000,156600.0,156680.0,156290.0,156380.0,4398
3,SPFB.RTS,5,20200103,101500,156380.0,156390.0,156100.0,156160.0,4382
4,SPFB.RTS,5,20200103,102000,156140.0,156280.0,156090.0,156220.0,3164
...,...,...,...,...,...,...,...,...,...
157,SPFB.RTS,5,20200103,232500,155400.0,155400.0,155280.0,155290.0,607
158,SPFB.RTS,5,20200103,233000,155290.0,155380.0,155280.0,155370.0,527
159,SPFB.RTS,5,20200103,233500,155360.0,155480.0,155350.0,155430.0,490
160,SPFB.RTS,5,20200103,234000,155450.0,155470.0,155410.0,155450.0,224
161,SPFB.RTS,5,20200103,234500,155450.0,155510.0,155400.0,155440.0,881

Делаем слияние столбцов (полей) DATE и TIME. Оставляем между ними пробел для более удобного преобразования типов

In [13]:
df_data['date_time'] = df_data['<DATE>'].astype(str) + ' ' + df_data['<TIME>'].astype(str)  # Слияние столбцов
df_data

,<TICKER>,<PER>,<DATE>,<TIME>,<OPEN>,<HIGH>,<LOW>,<CLOSE>,<VOL>,date_time
0,SPFB.RTS,5,20200103,100000,154670.0,156720.0,154670.0,156610.0,13396,20200103 100000
1,SPFB.RTS,5,20200103,100500,156600.0,156680.0,156500.0,156610.0,4957,20200103 100500
2,SPFB.RTS,5,20200103,101000,156600.0,156680.0,156290.0,156380.0,4398,20200103 101000
3,SPFB.RTS,5,20200103,101500,156380.0,156390.0,156100.0,156160.0,4382,20200103 101500
4,SPFB.RTS,5,20200103,102000,156140.0,156280.0,156090.0,156220.0,3164,20200103 102000
...,...,...,...,...,...,...,...,...,...,...
157,SPFB.RTS,5,20200103,232500,155400.0,155400.0,155280.0,155290.0,607,20200103 232500
158,SPFB.RTS,5,20200103,233000,155290.0,155380.0,155280.0,155370.0,527,20200103 233000
159,SPFB.RTS,5,20200103,233500,155360.0,155480.0,155350.0,155430.0,490,20200103 233500
160,SPFB.RTS,5,20200103,234000,155450.0,155470.0,155410.0,155450.0,224,20200103 234000
161,SPFB.RTS,5,20200103,234500,155450.0,155510.0,155400.0,155440.0,881,20200103 234500

In [14]:
df_data = df_data.set_index(pd.DatetimeIndex(df_data['date_time']))  # Меняем индекс и делаем её типом date
df_data

,<TICKER>,<PER>,<DATE>,<TIME>,<OPEN>,<HIGH>,<LOW>,<CLOSE>,<VOL>,date_time
date_time,,,,,,,,,,
2020-01-03 10:00:00,SPFB.RTS,5,20200103,100000,154670.0,156720.0,154670.0,156610.0,13396,20200103 100000
2020-01-03 10:05:00,SPFB.RTS,5,20200103,100500,156600.0,156680.0,156500.0,156610.0,4957,20200103 100500
2020-01-03 10:10:00,SPFB.RTS,5,20200103,101000,156600.0,156680.0,156290.0,156380.0,4398,20200103 101000
2020-01-03 10:15:00,SPFB.RTS,5,20200103,101500,156380.0,156390.0,156100.0,156160.0,4382,20200103 101500
2020-01-03 10:20:00,SPFB.RTS,5,20200103,102000,156140.0,156280.0,156090.0,156220.0,3164,20200103 102000
...,...,...,...,...,...,...,...,...,...,...
2020-01-03 23:25:00,SPFB.RTS,5,20200103,232500,155400.0,155400.0,155280.0,155290.0,607,20200103 232500
2020-01-03 23:30:00,SPFB.RTS,5,20200103,233000,155290.0,155380.0,155280.0,155370.0,527,20200103 233000
2020-01-03 23:35:00,SPFB.RTS,5,20200103,233500,155360.0,155480.0,155350.0,155430.0,490,20200103 233500
2020-01-03 23:40:00,SPFB.RTS,5,20200103,234000,155450.0,155470.0,155410.0,155450.0,224,20200103 234000
2020-01-03 23:45:00,SPFB.RTS,5,20200103,234500,155450.0,155510.0,155400.0,155440.0,881,20200103 234500

In [15]:
df_data = df_data.drop('date_time', 1)  # Удаляем ненужную колонку. 1 означает, что отбрасываем колонку а не индекс
df_data

,<TICKER>,<PER>,<DATE>,<TIME>,<OPEN>,<HIGH>,<LOW>,<CLOSE>,<VOL>
date_time,,,,,,,,,
2020-01-03 10:00:00,SPFB.RTS,5,20200103,100000,154670.0,156720.0,154670.0,156610.0,13396
2020-01-03 10:05:00,SPFB.RTS,5,20200103,100500,156600.0,156680.0,156500.0,156610.0,4957
2020-01-03 10:10:00,SPFB.RTS,5,20200103,101000,156600.0,156680.0,156290.0,156380.0,4398
2020-01-03 10:15:00,SPFB.RTS,5,20200103,101500,156380.0,156390.0,156100.0,156160.0,4382
2020-01-03 10:20:00,SPFB.RTS,5,20200103,102000,156140.0,156280.0,156090.0,156220.0,3164
...,...,...,...,...,...,...,...,...,...
2020-01-03 23:25:00,SPFB.RTS,5,20200103,232500,155400.0,155400.0,155280.0,155290.0,607
2020-01-03 23:30:00,SPFB.RTS,5,20200103,233000,155290.0,155380.0,155280.0,155370.0,527
2020-01-03 23:35:00,SPFB.RTS,5,20200103,233500,155360.0,155480.0,155350.0,155430.0,490
2020-01-03 23:40:00,SPFB.RTS,5,20200103,234000,155450.0,155470.0,155410.0,155450.0,224
2020-01-03 23:45:00,SPFB.RTS,5,20200103,234500,155450.0,155510.0,155400.0,155440.0,881

In [16]:
title_lst = df_data.columns.values  # Проверяем, что есть в заголовке
title_lst

array(['<TICKER>', '<PER>', '<DATE>', '<TIME>', '<OPEN>', '<HIGH>',
       '<LOW>', '<CLOSE>', '<VOL>'], dtype=object)

В заголовке нужно избавиться от знаков "меньше" и "больше" и привести к нижнему регистру (смена регистра нужна для БД)

In [17]:
# Удаляем ненужные символы
title_lst_new = [x.replace('<', '') for x in title_lst]  # Удаляем символ '<' в каждом элементе списка
title_lst_new = [x.replace('>', '') for x in title_lst_new]  # Удаляем символ '>' в каждом элементе списка
title_lst_new  # Отображаем список с новыми заголовками

['TICKER', 'PER', 'DATE', 'TIME', 'OPEN', 'HIGH', 'LOW', 'CLOSE', 'VOL']

In [18]:
# Приводим список с новыми заголовками к нижнему регистру
title_lst_new = [x.lower() for x in title_lst_new]
title_lst_new

['ticker', 'per', 'date', 'time', 'open', 'high', 'low', 'close', 'vol']

In [19]:
# Создаем словарь для переименования заголовка
rename_dic = dict(zip(title_lst, title_lst_new))
rename_dic

{'<TICKER>': 'ticker',
 '<PER>': 'per',
 '<DATE>': 'date',
 '<TIME>': 'time',
 '<OPEN>': 'open',
 '<HIGH>': 'high',
 '<LOW>': 'low',
 '<CLOSE>': 'close',
 '<VOL>': 'vol'}

In [20]:
# Переименовываем заголовок
df_data = df_data.rename(columns = rename_dic)
df_data

,ticker,per,date,time,open,high,low,close,vol
date_time,,,,,,,,,
2020-01-03 10:00:00,SPFB.RTS,5,20200103,100000,154670.0,156720.0,154670.0,156610.0,13396
2020-01-03 10:05:00,SPFB.RTS,5,20200103,100500,156600.0,156680.0,156500.0,156610.0,4957
2020-01-03 10:10:00,SPFB.RTS,5,20200103,101000,156600.0,156680.0,156290.0,156380.0,4398
2020-01-03 10:15:00,SPFB.RTS,5,20200103,101500,156380.0,156390.0,156100.0,156160.0,4382
2020-01-03 10:20:00,SPFB.RTS,5,20200103,102000,156140.0,156280.0,156090.0,156220.0,3164
...,...,...,...,...,...,...,...,...,...
2020-01-03 23:25:00,SPFB.RTS,5,20200103,232500,155400.0,155400.0,155280.0,155290.0,607
2020-01-03 23:30:00,SPFB.RTS,5,20200103,233000,155290.0,155380.0,155280.0,155370.0,527
2020-01-03 23:35:00,SPFB.RTS,5,20200103,233500,155360.0,155480.0,155350.0,155430.0,490
2020-01-03 23:40:00,SPFB.RTS,5,20200103,234000,155450.0,155470.0,155410.0,155450.0,224
2020-01-03 23:45:00,SPFB.RTS,5,20200103,234500,155450.0,155510.0,155400.0,155440.0,881